# Generated by Django 3.2.16 on 2023-03-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('pub_date',), 'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
    ]
